# Generated by Django 4.2.5 on 2023-09-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identificacion', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.EmailField(max_length=254)),
                ('Departamento', models.CharField(max_length=20)),
                ('Ciudad', models.CharField(max_length=20)),
                ('Edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Personas', models.IntegerField()),
                ('Observaciones', models.TextField()),
                ('Estado', models.CharField(default='No confirmado', max_length=10)),
                ('motivo', models.CharField(choices=[('evento_empresarial', 'Evento empresarial'), ('despedida_empresa', 'Despedida de la empresa'), ('desayuno_comercial', 'Desayuno comercial'), ('almuerzo', 'Almuerzo')], default='evento_empresarial', max_length=20)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalonesEmpresariales.cliente')),
            ],
        ),
    ]
