# Generated by Django 4.2.5 on 2023-09-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonesEmpresariales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='Estado',
            field=models.CharField(choices=[('Confirmado', 'Confirmado'), ('No Confirmado', 'No Confirmado')], default='No confirmado', max_length=20),
        ),
    ]
